import type { Car } from "./types";

const D = 24 * 60 * 60 * 1000;
const now = Date.now();

const IMG = {
  camry: "https://image.qwenlm.ai/generated-images/4778eba5-6cad-413f-b014-3be72fb6e379/_result.png",
  x5: "https://image.qwenlm.ai/generated-images/75442256-70d2-44b9-8e31-204b55d070c9/_result.png",
  rio: "https://image.qwenlm.ai/generated-images/c71edde0-d075-48a1-b0a5-f4a37e7dd62c/_result.png",
  creta: "https://image.qwenlm.ai/generated-images/d2ae7d31-cce8-4cb3-9aef-987acb662ca1/_result.png",
  tiguan: "https://image.qwenlm.ai/generated-images/8d25d843-64ae-43e8-a135-3829916078e9/_result.png",
  octavia: "https://image.qwenlm.ai/generated-images/d73e2654-e7c7-4e60-bcd8-0d9c5cd6bc16/_result.png",
};

export const SEED_CARS: Car[] = [
  {
    id: "seed-1",
    photo: IMG.camry,
    make: "Toyota",
    model: "Camry",
    year: 2021,
    country: "Япония",
    trim: "Элеганс",
    mileage: 45000,
    drive: "Передний",
    engine: "2.5 л",
    gearbox: "Автомат",
    color: "Серебристый",
    price: 2890000,
    addedAt: now - 2 * D,
  },
  {
    id: "seed-2",
    photo: IMG.x5,
    make: "BMW",
    model: "X5",
    year: 2019,
    country: "Германия",
    trim: "xLine",
    mileage: 78500,
    drive: "Полный",
    engine: "3.0 л",
    gearbox: "Автомат",
    color: "Чёрный",
    price: 5450000,
    addedAt: now - 5 * D,
  },
  {
    id: "seed-3",
    photo: IMG.rio,
    make: "Kia",
    model: "Rio",
    year: 2022,
    country: "Россия",
    trim: "Comfort",
    mileage: 12300,
    drive: "Передний",
    engine: "1.6 л",
    gearbox: "Механика",
    color: "Красный",
    price: 1650000,
    addedAt: now - 1 * D,
  },
  {
    id: "seed-4",
    photo: IMG.creta,
    make: "Hyundai",
    model: "Creta",
    year: 2021,
    country: "Россия",
    trim: "Lifestyle",
    mileage: 34800,
    drive: "Полный",
    engine: "2.0 л",
    gearbox: "Автомат",
    color: "Белый",
    price: 2150000,
    addedAt: now - 8 * D,
  },
  {
    id: "seed-5",
    photo: IMG.tiguan,
    make: "Volkswagen",
    model: "Tiguan",
    year: 2020,
    country: "Германия",
    trim: "Respect",
    mileage: 61200,
    drive: "Передний",
    engine: "1.4 л",
    gearbox: "Робот",
    color: "Серый",
    price: 2590000,
    addedAt: now - 12 * D,
  },
  {
    id: "seed-6",
    photo: IMG.octavia,
    make: "Škoda",
    model: "Octavia",
    year: 2020,
    country: "Чехия",
    trim: "Ambition",
    mileage: 88900,
    drive: "Передний",
    engine: "1.6 л",
    gearbox: "Механика",
    color: "Синий",
    price: 1990000,
    addedAt: now - 15 * D,
  },
];
